version: "3.6"

x-deploy:
  &default-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s

# ============================================================================ #

services:
  pureftp:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
    ports:
      - "21:21"
      # see FTP_PASSIVE_PORTS, make sure to bind to the SAME EXACT ports
      - "30000-30009:30000-30009"
    volumes:
      # make sure you actually create these:
      - "/home/pure-ftpd/ftpusers:/home/ftpusers"
      - "/home/pure-ftpd/passwd:/etc/pure-ftpd/passwd"
    environment:
      # set IP of your docker host as PUBLICHOST
      PUBLICHOST: "localhost"
      # Passive ports should be set to be the same as the host
      FTP_PASSIVE_PORTS: "30000:30009"
      FTP_USER_NAME: "ftpuser"
      FTP_USER_PASS: "ftpuser"
      FTP_USER_HOME: "/home/ftpusers"
      FTP_MAX_CLIENTS: "50"
    deploy:
      << : *default-deploy
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
